CREATE TABLE supplier(SNO TEXT PRIMARY KEY,SNAME TEXT,STATUS INTEGER,CITY TEXT);
INSERT INTO supplier(SNO,SNAME,STATUS,CITY)
VALUES ("S1","ALEX",20,"LONDON"),("S2","STEVE",30,"DELHI"),("S3","JOHN",25,"PARIS"),("S4","CLARK",35,"WASHINGTON DC"),("S5","BRUCE",40,"GOTHAM CITY");
SELECT*FROM supplier;
