CREATE TABLE products( PRODUCTID TEXT, PRODUCTNAME TEXT, SUPPLIERID TEXT, CATEGORYID TEXT, UNIT TEXT, PRICE REAL);
INSERT INTO products(PRODUCTID,PRODUCTNAME,SUPPLIERID,CATEGORYID,UNIT,PRICE)
VALUES("1","laptop","23","12","1",20000),
("2","Lego","24","11","1",10000),
("3","Juice","21","7","200 ml",20),
("4","Shampoo","27","9","150 ml",200),
("5","Milk","28","7","250 ml",25);
SELECT COUNT(PRODUCTID) AS PRODUCTCOUNT FROM products;
SELECT AVG(PRICE) AS AVERAGEPRICE FROM products;
SELECT SUM(PRICE) AS SUMPRICE FROM products;
SELECT* FROM products;