CREATE TABLE IF NOT EXISTS marks(ROLLNO TEXT, NAME TEXT, ENGLISH REAL,SCIENCE REAL, MATH REAL, SST REAL);
INSERT INTO marks(ROLLNO,NAME,ENGLISH,SCIENCE,MATH,SST) 
VALUES("10","Aarav",80,90,95,86),
("11","Aayan",86,90,75,99),
("12","Aarya",90,87,95,80),
("13","Aasma",97,98,94,97),
("14","Ananya",93,79,91,86);
SELECT* FROM marks;
SELECT COUNT(NAME) AS NAMECOUNT FROM marks;
SELECT AVG(ENGLISH) AS ENGLISHAVG FROM marks;
SELECT ENGLISH FROM marks WHERE ROLLNO=11; 
SELECT ENGLISH,SCIENCE,MATH,SST FROM marks WHERE ROLLNO=11;
SELECT SUM(ENGLISH) FROM marks;