CREATE TABLE IF NOT EXISTS NOBELWINS(YEAR INTEGER,SUBJECT TEXT,NAME TEXT,COUNTRY TEXT,CATEGORY TEXT);
INSERT INTO NOBELWINS(YEAR,SUBJECT,NAME,COUNTRY,CATEGORY) 
VALUES
(1970, 'PHYSICS', 'HANNES ALFVEN', 'SWEDEN', 'SCIENTIST'),
(1970, 'PHYSICS', 'LOUIS NEEL', 'FRANCE', 'SCIENTIST'),
(1971, 'PHYSICS', 'PAUL', 'FRANCE', 'SCIENTIST'),
(1971, 'CHEMISTRY', 'HAMILTON', 'SWEDEN', 'LINGUIST'),
(1972, 'LITERATURE', 'BERNARD KELSON', 'GERMANY', 'ECONOMIST'),
(1972, 'ECONOMICS', 'JOSEPH', 'RUSSIA', 'ECONOMIST'),
(1973, 'BIOLOGY', 'PHILIPS', 'USA', 'PRIME MINISTER'),
(1980, 'BIOLOGY', 'MARTIN', 'USA', 'PRESIDENT'),
(1981, 'PHYSIOLOGY', 'HANNAH', 'HUNGARY', 'SCIENTIST'),
(1975, 'PHYSICS', 'PETER', 'CHILE', 'SCIENTIST');
SELECT* FROM NOBELWINS WHERE SUBJECT NOT LIKE "B%";
SELECT* FROM NOBELWINS WHERE NAME NOT LIKE "P%";
SELECT* FROM NOBELWINS WHERE NAME NOT LIKE "%L";
SELECT* FROM NOBELWINS WHERE SUBJECT NOT LIKE "%H%";